sudo: required

language: bash

services:
    - docker

before_install:
    - docker build -t hgi/sequencescape-python-client_testing -f docker/tests/Dockerfile .

script:
    - docker run hgi/sequencescape-python-client_testing
